# Workflow Name
name: CI

# Define when to trigger the workflow
on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Install Chromium (for headless browser testing)
      - name: Install Chromium browser
        run: sudo apt-get install -y chromium-browser

      # Step 3: Install QUnit CLI (for running tests)
      - name: Install QUnit CLI
        run: npm install -g qunit

      # Step 4: Run QUnit tests
      - name: Run QUnit tests
        run: |
          npx qunit --browser chromium index.html

      # Step 5: Install Docker Engine (for building the Docker image)
      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      # Step 6: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 .

      # Step 8: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
