name: Static App Test

on:
  push:
    branches:
      - main

jobs:
  test-static-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install http-server
        run: npm install -g http-server

      - name: Start HTTP server
        run: |
          nohup http-server . -p 8080 -c-1 &
          sleep 5

      - name: Test with curl
        run: |
          curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/index.html > test-reports/results.log

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: test-reports/results.log

      # Step 6: Install Docker Engine
      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      # Step 7: Log in to Docker Hub
      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Build the Docker image
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 .

      # Step 9: Push the Docker image to Docker Hub
      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
