# Workflow Name
name: CI

# Define when to trigger the workflow
on:
  push: # The event that occurs
    branches:
        - main
jobs:
    print-greeting:
        runs-on: ubuntu-latest

        # Define steps to execute
        steps:
          - name: Check out the code # This checkouts the github repository created
            uses: actions/checkout@v3

          - name: Print Greeting
            run: |
                ```
                 #!/bin/bash
                 mkdir user
                 cd user
                 touch name.txt
                 echo "Hello World!" > name.txt
                 ```