name: CI

on:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Install Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Copy files to Nginx's root directory
        run: |
          # Ensure permissions and clean up previous HTML directory
          sudo chmod -R 777 /var/www
          sudo chown -R $USER:$USER /var/www
          sudo rm -rf /var/www/html
          sudo mkdir /var/www/html

          # Copy files from the checked-out code to Nginx's root directory
          sudo cp -r * /var/www/html

          # Restart Nginx to serve the new files
          sudo systemctl restart nginx
          sleep 5

      - name: Check if app is accessible using curl
        run: |
          curl -f http://localhost:80/index.html > result.log || echo "App not accessible" > result.log

      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: result.log

      - name: Install Docker Engine
        uses: docker/setup-buildx-action@v2
        with:
          version: 'latest'

      - name: Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0 .

      - name: Install Trivy
        run: |
          set -e
          curl -sfl https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -x
          # Check if the trivy binary is present
          ls -l ./bin || echo "Trivy binary not found"
          # Move the binary to the desired location
          sudo mv ./bin/trivy /usr/local/bin/trivy
          sudo chmod +x /usr/local/bin/trivy

      - name: Verify Trivy installation
        run: |
          trivy --version
      
      - name: Scan the Docker image
        run: |
            trivy image --format json --output trivy-scan-report.json ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0
        
      - name: Upload Trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: trivy-scan-report.json

      - name: Push the Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/new-image:1.0.0